# Generated by Django 5.2.11 on 2026-02-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_device_id', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=2000)),
                ('image_token', models.CharField(blank=True, max_length=500)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleNestToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField()),
                ('classification', models.CharField(choices=[('crane_active', 'Crane Active'), ('crane_idle', 'Crane Idle'), ('barge_present', 'Barge Present'), ('barge_absent', 'No Barge'), ('loading', 'Loading Operations'), ('unloading', 'Unloading Operations'), ('idle', 'Dock Idle'), ('obstructed', 'View Obstructed'), ('night', 'Nighttime/Low Visibility'), ('unknown', 'Unknown')], max_length=50)),
                ('confidence', models.FloatField()),
                ('details', models.TextField(blank=True)),
                ('model_used', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='camera.camerasnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
